// GENERIC
export const REQUEST_TODO = "REQUEST_TODO";
export const FAILURE_TODO = "FAILURE_TODO";
// ENDIVIDUAL
export const GET_SUCCESS_TODO = "GET_SUCCESS_TODO";
export const POST_SUCCESS_TODO = "POST_SUCCESS_TODO";
